### ISSUE TITLE
Error when no vss is chosen

### ISSUE THREAD

**Issue by coolcalmcollected22** [Silv3rHorn/ArtifactExtractor#2]
If you elect not to enter a value for vss with the compiled EXE you get the following error:

Traceback (most recent call last):
  File "artifact_extractor.py", line 309, in <module>
  File "artifact_extractor.py", line 284, in main
  File "dfvfs\helpers\volume_scanner.pyc", line 387, in GetBasePathSpecs
  File "dfvfs\helpers\volume_scanner.pyc", line 211, in _ScanVolume
  File "dfvfs\helpers\volume_scanner.pyc", line 247, in _ScanVolumeScanNode
  File "dfvfs\helpers\volume_scanner.pyc", line 304, in _ScanVolumeScanNodeVSS
AttributeError: 'str' object has no attribute 'reverse'

Is this something to be checked in the source or perhaps on my end?

**Comment by Silv3rHorn** [comment]
Hi,

I will push out a fix for this within the next couple of days. In the meantime, you can enter a random string (e.g. 'none') instead of not entering any value to skip the extraction from vss .

**Comment by Silv3rHorn** [comment]
Fixed in c383161

**Comment by coolcalmcollected22** [comment]
Awesome! Keep up the great work sir!
